micronaut:
  application:
    name: mnQuickstart
  server:
    port: ${SERVER_PORT:8090}


hello:
  default:
    message: "Default hello message here"
  translation:
    de: "Hallo Welt"
    es: "Hola mundo"